### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by elaltito** [BaguetteEngineering/annotations-sketch-plugin#1]
Hi There,

Great plugin! very useful :)

Maybe you could also add a functionality to name the current selection to "Annotation" too. To avoid having to manually rename all annotation layers. I think this would make the plugin even better! :)

**Comment by bastienpetit** [comment]
Hi @elaltito,

Thank you for suggesting this, great idea!

Done with with [v0.4.0](https://github.com/BaguetteEngineering/annotations-sketch-plugin/releases/tag/v0.4.0). The new command looks like this:

<img width="670" alt="screen shot 2018-12-27 at 10 20 03" src="https://user-images.githubusercontent.com/194437/50483459-381f0680-09ec-11e9-81c1-ff3a3d84321e.png">

If you need to run it on many Artboards/Pages, you can use the keyboard shortcut of the "Run Again" command:

<img width="670" alt="screen shot 2018-12-27 at 10 26 15" src="https://user-images.githubusercontent.com/194437/50483467-43723200-09ec-11e9-9a24-5190bcc50756.png">

Have a nice day!

**Comment by elaltito** [comment]
Hi @bastienpetit,
Looks great, I'm glad you liked the idea! Good work on getting it done so quickly 👍 

I look forward to using it a lot in the future! :)
