### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by SuperGNUS** [BaguetteEngineering/annotations-sketch-plugin#11]
Please add a license to this plugin.  Preferably Apache 2/MIT or BSD license.

**Comment by SuperGNUS** [comment]
It's simple to do and it's useless without it.

Open your GitHub repository in a browser.
In the root directory, click on Create new file .
Name the file “LICENSE”.
Click on Choose a license template .
Pick one of the licenses (all the ones mentioned in this article are there).
Once chosen, click on Review and submit .
Commit the file.

**Comment by julienma** [comment]
Done: https://github.com/BaguetteEngineering/annotations-sketch-plugin/blob/master/LICENSE
