### ISSUE TITLE
annotations.sketchplugin does not excist 

### ISSUE THREAD

**Issue by OsSi3** [BaguetteEngineering/annotations-sketch-plugin#2]
The plugin "annotations.sketchplugin" does not show up when i extract the map

**Comment by julienma** [comment]
@OsSi3 you need to download the 1st asset of the [release](https://github.com/BaguetteEngineering/annotations-sketch-plugin/releases/tag/v0.4.0) and unzip it.

![Screenshot 2019-05-17 at 10 48 31](https://user-images.githubusercontent.com/201897/57915589-6022df80-7891-11e9-9511-ff6d5f5ec5aa.png)
